module.exports = {
  sidebarPt: [
    {
      type: 'category',
      label: 'Início',
      collapsible: false,
      collapsed: false,
      items: [
        'pt/visao-geral',
        'pt/introducao',
        'pt/modelos',
        {
          type: 'category',
          label: 'API',
          collapsible: false,
          collapsed: false,
          items: [
            'pt/api/comeco-rapido',
            'pt/api/openai-compatibilidade',
            'pt/chamada-funcao',
            'pt/structured-outputs',
            'pt/embeddings+Sabia-3+RAG',
            'pt/rate-limits',
            'pt/batch-api',
            'pt/files',
            {
              type: 'category',
              label: 'Exemplos',
              collapsible: false,
              collapsed: false,
              items: [
                'pt/examples/langchain',
                'pt/examples/langgraph',
                'pt/examples/llama-index',
                'pt/examples/csharp-js',
              ],
            },
            'pt/biblioteca',
            'pt/casos-de-uso-carrossel',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Recursos',
      collapsible: false,
      collapsed: false,
      items: [
        'pt/glossario',
        'pt/status',
        'pt/system',
        'pt/deletar-conta',
      ],
    },
  ],
  sidebarEn: [
    {
      type: 'category',
      label: 'Home',
      collapsible: false,
      collapsed: false,
      items: [
        'en/overview',
        'en/introduction',
        'en/models',
        {
          type: 'category',
          label: 'API',
          collapsible: false,
          collapsed: false,
          items: [
            'en/api/quick-start',
            'en/api/openai-compatibility',
            'en/function-call',
            'en/structured-outputs',
            'en/embeddings+Sabia-3+RAG',
            'en/rate-limits',
            'en/batch-api',
            'en/files',
            {
              type: 'category',
              label: 'Examples',
              collapsible: false,
              collapsed: false,
              items: [
                'en/examples/langchain',
                'en/examples/langgraph',
                'en/examples/llama-index',
                'en/examples/csharp-js',
              ],
            },
            'en/library',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsible: false,
      collapsed: false,
      items: [
        'en/glossary',
        'en/status',
        'en/system',
        'en/delete-account',
      ],
    },
  ],
};
